<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'RazorLight'">
    <!-- This is what currently determines the package version. -->
    <Version>2.3.1</Version>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSource>true</EmbedUntrackedSource>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>

    <RepositoryUrl>https://github.com/dijgrid/razor-light</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'RazorLight'">
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'RazorLight'">
    <SourceRoot Include="$(NuGetPackageRoot)" Condition="'$(NuGetPackageRoot)' != ''" />
  </ItemGroup>
</Project>
