<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference
      Include="../../src/RazorLight/RazorLight.csproj"
      GlobalPropertiesToRemove="EnableAotAnalyzer;EnableSingleFileAnalyzer;EnableTrimAnalyzer;IncludeAllContentForSelfExtract;PublishAot;PublishSingleFile;PublishTrimmed;RuntimeIdentifier;SelfContained" />
  </ItemGroup>
</Project>
