<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RazorLight.Precompile\RazorLight.Precompile.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Samples\SharedComposition.cs" />
    <None Include="Samples\SharedComposition.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Samples\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Update="SamplesWithBaseDir\MessageItem.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SamplesWithBaseDir\FullMessage.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
